import { chromium } from "@playwright/test";
const base = "http://localhost:3000";
const b = await chromium.launch(); const ctx = await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}); const page = await ctx.newPage();
const errors=[]; page.on("pageerror",e=>errors.push("PAGEERROR "+e.message.slice(0,150)));
page.on("response",r=>{ if(r.status()>=400) errors.push(`HTTP ${r.status()} ${r.request().method()} ${r.url().replace(base,"")}`); });
const text = async () => (await page.locator("body").innerText()).replace(/\n{2,}/g,"\n");
await page.goto(base+"/book/demo"); await page.waitForTimeout(1200);
await page.getByRole("button",{name:/Skin fade/}).click();
await page.getByRole("button",{name:"Choose your barber",exact:true}).click();
await page.waitForTimeout(500); console.log("--- barber step ---\n", (await text()).match(/STEP 02[\s\S]{0,900}/)?.[0]);
await page.screenshot({path:"/tmp/flow-2.png", fullPage:true});
await page.getByRole("button",{name:/Jay Carter/}).click();
await page.getByRole("button",{name:"Find a time",exact:true}).click(); await page.waitForTimeout(800);
console.log("--- time step ---\n", (await text()).match(/STEP 03[\s\S]{0,1200}/)?.[0]);
await page.screenshot({path:"/tmp/flow-3.png", fullPage:true});
await page.getByRole("button",{name:/Tomorrow/}).first().click(); await page.waitForTimeout(600);
await page.getByRole("button",{name:"Your details",exact:true}).click(); await page.waitForTimeout(500);
console.log("--- details step ---\n", (await text()).match(/STEP 04[\s\S]{0,1200}/)?.[0]);
await page.screenshot({path:"/tmp/flow-4.png", fullPage:true});
await page.getByLabel("Your name").fill("Audit Tester"); await page.getByLabel("Mobile number").fill("07700 900999"); await page.getByLabel("Email address (optional)").fill("audit@example.test");
await page.getByRole("button",{name:"Review booking"}).click(); await page.waitForTimeout(500);
console.log("--- review step ---\n", (await text()).match(/STEP 05[\s\S]{0,1400}/)?.[0]);
await page.screenshot({path:"/tmp/flow-5.png", fullPage:true});
await page.getByRole("button",{name:"Confirm booking"}).click(); await page.waitForTimeout(2500);
console.log("--- confirmation ---\nurl:", page.url(), "\n", (await text()).slice(0,2200));
await page.screenshot({path:"/tmp/flow-done.png", fullPage:true});
console.log("ERRORS", errors);
await b.close();
